---
- name: copy the banner content
  hosts: web
  become: yes
  tasks:
    - name: copy the banner 
      ansible.builtin.copy:
        content: "Sun set down in east"
        dest: /etc/motd.d/banner



