---
- name: copy the content to banner 
  hosts: web
  become: yes
  tasks:
    - name: copy the content 
      ansible.builtin.copy:
        content: "Sun set down in east"
        dest: /var/www/html/index.html
