---
- name: copy the content to message of the day banner
  hosts: web
  become: yes
  tasks:
    - name: copy the content to banner file
      ansible.builtin.copy:
        content: "Sun set down in east"
        dest: /etc/motd.d/banner
